-- PUBLIC.CLI_EMPRESA DEFINITION

-- DROP TABLE

-- DROP TABLE PUBLIC.CLI_EMPRESA;

CREATE TABLE PUBLIC.CLI_EMPRESA (
	ID_EMPRESA BIGSERIAL NOT NULL,
	AUD_UPDATED_AT TIMESTAMP NOT NULL,
	AUD_UPDATED_BY VARCHAR(50) NOT NULL,
	AUD_VERSION INT8 NOT NULL,
	VD_ACTIVIDAD VARCHAR(30) NOT NULL,
	VD_AFILIACIONES VARCHAR(200) NOT NULL,
	DESCRIPCION VARCHAR(300) NOT NULL,
	VF_ESTADO VARCHAR(30) NOT NULL,
	FECHA_FUNDACION VARCHAR(10) NOT NULL,
	FECHA_OPERACION VARCHAR(10) NOT NULL,
	REF_KEY VARCHAR(30) NOT NULL,
	REF_NAME VARCHAR(150) NOT NULL,
	VD_TIPO VARCHAR(30) NOT NULL,
	CONSTRAINT CLI_EMPRESA_PKEY PRIMARY KEY (ID_EMPRESA)
);


-- PUBLIC.LOG_CONSULTA DEFINITION

-- DROP TABLE

-- DROP TABLE PUBLIC.LOG_CONSULTA;

CREATE TABLE PUBLIC.LOG_CONSULTA (
	ID_CONSULTA BIGSERIAL NOT NULL,
	AUD_UPDATED_AT TIMESTAMP NOT NULL,
	AUD_UPDATED_BY VARCHAR(50) NOT NULL,
	AUD_VERSION INT8 NOT NULL,
	DATA_RESPUESTA VARCHAR(1024) NULL,
	DATA_SOLICITUD VARCHAR(1024) NULL,
	VD_ESTADO VARCHAR(30) NOT NULL,
	FECHA_CONSULTA TIMESTAMP NULL,
	VD_TIPO VARCHAR(30) NOT NULL,
	CONSTRAINT LOG_CONSULTA_PKEY PRIMARY KEY (ID_CONSULTA)
);


-- PUBLIC.PAR_DOMINIO DEFINITION

-- DROP TABLE

-- DROP TABLE PUBLIC.PAR_DOMINIO;

CREATE TABLE PUBLIC.PAR_DOMINIO (
	ID_DOMINIO BIGSERIAL NOT NULL,
	AUD_UPDATED_AT TIMESTAMP NOT NULL,
	AUD_UPDATED_BY VARCHAR(50) NOT NULL,
	AUD_VERSION INT8 NOT NULL,
	CODIGO VARCHAR(50) NOT NULL,
	VF_ESTADO VARCHAR(30) NOT NULL,
	NOMBRE_CAMPO VARCHAR(50) NOT NULL,
	NOMBRE_TABLA VARCHAR(50) NOT NULL,
	VD_TIPO VARCHAR(30) NOT NULL,
	CONSTRAINT PAR_DOMINIO_PKEY PRIMARY KEY (ID_DOMINIO)
);


-- PUBLIC.SEG_CORREO DEFINITION

-- DROP TABLE

-- DROP TABLE PUBLIC.SEG_CORREO;

CREATE TABLE PUBLIC.SEG_CORREO (
	ID_CORREO BIGSERIAL NOT NULL,
	AUD_UPDATED_AT TIMESTAMP NOT NULL,
	AUD_UPDATED_BY VARCHAR(50) NOT NULL,
	AUD_VERSION INT8 NOT NULL,
	CORREO_COPIA VARCHAR(300) NULL,
	CORREO_DESTINO VARCHAR(300) NOT NULL,
	VF_ESTADO VARCHAR(30) NOT NULL,
	FECHA_SOLICITUD TIMESTAMP NOT NULL,
	FECHA_USO TIMESTAMP NULL,
	FECHA_VIGENCIA TIMESTAMP NOT NULL,
	ID_REFERENCIA VARCHAR(50) NOT NULL,
	VD_PLANTILLA VARCHAR(30) NOT NULL,
	VD_TIPO VARCHAR(30) NOT NULL,
	VALOR_TOKEN VARCHAR(40) NULL,
	CONSTRAINT SEG_CORREO_PKEY PRIMARY KEY (ID_CORREO)
);


-- PUBLIC.SEG_PERSONA DEFINITION

-- DROP TABLE

-- DROP TABLE PUBLIC.SEG_PERSONA;

CREATE TABLE PUBLIC.SEG_PERSONA (
	ID_PERSONA BIGSERIAL NOT NULL,
	AUD_UPDATED_AT TIMESTAMP NOT NULL,
	AUD_UPDATED_BY VARCHAR(50) NOT NULL,
	AUD_VERSION INT8 NOT NULL,
	COMPLEMENTO_DOCUMENTO VARCHAR(30) NULL,
	DIRECCION VARCHAR(300) NOT NULL,
	FIRM_ARCHIVO OID NULL,
	FIRM_NOMBRE VARCHAR(255) NULL,
	FIRM_TIPO VARCHAR(255) NULL,
	DOC_ARCHIVO OID NULL,
	DOC_NOMBRE VARCHAR(255) NULL,
	DOC_TIPO VARCHAR(255) NULL,
	VF_ESTADO VARCHAR(30) NOT NULL,
	VD_EXPEDICION_DOCUMENTO VARCHAR(30) NOT NULL,
	FECHA_NACIMIENTO TIMESTAMP NOT NULL,
	VD_GENERO VARCHAR(30) NOT NULL,
	NOMBRES VARCHAR(150) NOT NULL,
	NUMERO_CELULAR VARCHAR(30) NOT NULL,
	NUMERO_DOCUMENTO VARCHAR(30) NOT NULL,
	NUMERO_TELEFONICO VARCHAR(30) NOT NULL,
	VD_PAIS VARCHAR(30) NOT NULL,
	PRIMER_APELLIDO VARCHAR(100) NOT NULL,
	SEGUNDO_APELLIDO VARCHAR(100) NULL,
	VD_TIPO_DOCUMENTO VARCHAR(30) NOT NULL,
	CONSTRAINT SEG_PERSONA_PKEY PRIMARY KEY (ID_PERSONA)
);


-- PUBLIC.CLI_CATEGORIA DEFINITION

-- DROP TABLE

-- DROP TABLE PUBLIC.CLI_CATEGORIA;

CREATE TABLE PUBLIC.CLI_CATEGORIA (
	ID_CATEGORIA BIGSERIAL NOT NULL,
	AUD_UPDATED_AT TIMESTAMP NOT NULL,
	AUD_UPDATED_BY VARCHAR(50) NOT NULL,
	AUD_VERSION INT8 NOT NULL,
	VD_ACTIVOS_UFV VARCHAR(30) NULL,
	VD_CATEGORIA VARCHAR(30) NOT NULL,
	VF_ESTADO VARCHAR(30) NOT NULL,
	VD_EXPORTACIONES_RUBROS VARCHAR(300) NULL,
	VD_EXPORTACIONES_UFV VARCHAR(30) NULL,
	FECHA_REGISTRO TIMESTAMP NOT NULL,
	VD_IMPORTACIONES_RUBROS VARCHAR(300) NULL,
	VD_IMPORTACIONES_UFV VARCHAR(30) NULL,
	VD_NRO_EMPLEADOS VARCHAR(30) NULL,
	VD_VENTAS_UFV VARCHAR(30) NULL,
	ID_EMPRESA INT8 NOT NULL,
	CONSTRAINT CLI_CATEGORIA_PKEY PRIMARY KEY (ID_CATEGORIA),
	CONSTRAINT FKHR5WNXTSIGBNIQHFE4Q2GC5BP FOREIGN KEY (ID_EMPRESA) REFERENCES CLI_EMPRESA(ID_EMPRESA)
);


-- PUBLIC.CLI_CONTACTO DEFINITION

-- DROP TABLE

-- DROP TABLE PUBLIC.CLI_CONTACTO;

CREATE TABLE PUBLIC.CLI_CONTACTO (
	ID_CONTACTO BIGSERIAL NOT NULL,
	AUD_UPDATED_AT TIMESTAMP NOT NULL,
	AUD_UPDATED_BY VARCHAR(50) NOT NULL,
	AUD_VERSION INT8 NOT NULL,
	DESCRIPCION VARCHAR(300) NOT NULL,
	VF_ESTADO VARCHAR(30) NOT NULL,
	FECHA_REGISTRO TIMESTAMP NOT NULL,
	FECHA_VERFICACION TIMESTAMP NULL,
	NOMBRE VARCHAR(100) NULL,
	VD_TIPO VARCHAR(30) NOT NULL,
	VALOR VARCHAR(100) NULL,
	ID_EMPRESA INT8 NOT NULL,
	CONSTRAINT CLI_CONTACTO_PKEY PRIMARY KEY (ID_CONTACTO),
	CONSTRAINT FKPX8HFDCHWG2MQE59RS6RCGSWS FOREIGN KEY (ID_EMPRESA) REFERENCES CLI_EMPRESA(ID_EMPRESA)
);


-- PUBLIC.CLI_DIRECCION DEFINITION

-- DROP TABLE

-- DROP TABLE PUBLIC.CLI_DIRECCION;

CREATE TABLE PUBLIC.CLI_DIRECCION (
	ID_DIRECCION BIGSERIAL NOT NULL,
	AUD_UPDATED_AT TIMESTAMP NOT NULL,
	AUD_UPDATED_BY VARCHAR(50) NOT NULL,
	AUD_VERSION INT8 NOT NULL,
	AVENIDA VARCHAR(50) NOT NULL,
	CALLES VARCHAR(100) NULL,
	VD_DEPARTAMENTO VARCHAR(30) NOT NULL,
	DOMICILIO VARCHAR(100) NULL,
	EDIFICIO VARCHAR(100) NULL,
	VF_ESTADO VARCHAR(30) NOT NULL,
	FECHA_FIN TIMESTAMP NULL,
	FECHA_INICIO TIMESTAMP NULL,
	FECHA_REGISTRO TIMESTAMP NOT NULL,
	GEO_REFERENCIA VARCHAR(100) NULL,
	VD_MUNICIPIO VARCHAR(30) NOT NULL,
	NOMBRE VARCHAR(100) NULL,
	OFICINA VARCHAR(100) NULL,
	PISO VARCHAR(10) NULL,
	REFERENCIA VARCHAR(300) NULL,
	VD_TIPO VARCHAR(30) NOT NULL,
	ID_EMPRESA INT8 NOT NULL,
	CONSTRAINT CLI_DIRECCION_PKEY PRIMARY KEY (ID_DIRECCION),
	CONSTRAINT FKRLTFNEMYERI6WFRYWOY7TISL FOREIGN KEY (ID_EMPRESA) REFERENCES CLI_EMPRESA(ID_EMPRESA)
);


-- PUBLIC.CLI_DOCUMENTO DEFINITION

-- DROP TABLE

-- DROP TABLE PUBLIC.CLI_DOCUMENTO;

CREATE TABLE PUBLIC.CLI_DOCUMENTO (
	ID_DOCUMENTO BIGSERIAL NOT NULL,
	AUD_UPDATED_AT TIMESTAMP NOT NULL,
	AUD_UPDATED_BY VARCHAR(50) NOT NULL,
	AUD_VERSION INT8 NOT NULL,
	DESCRIPCION VARCHAR(300) NOT NULL,
	CONTENIDO_ARCHIVO OID NULL,
	NOMBRE_ARCHIVO VARCHAR(50) NULL,
	TIPO_ARCHIVO VARCHAR(50) NULL,
	VF_ESTADO VARCHAR(30) NOT NULL,
	FECHA_REGISTRO TIMESTAMP NOT NULL,
	FECHA_VERIFICACION TIMESTAMP NULL,
	NOMBRE VARCHAR(100) NULL,
	NUMERO VARCHAR(50) NULL,
	OBSERVACION VARCHAR(300) NULL,
	VD_TIPO VARCHAR(30) NOT NULL,
	VIGENCIA_DESDE TIMESTAMP NULL,
	VIGENCIA_HASTA TIMESTAMP NULL,
	ID_EMPRESA INT8 NOT NULL,
	CONSTRAINT CLI_DOCUMENTO_PKEY PRIMARY KEY (ID_DOCUMENTO),
	CONSTRAINT FKF308EVXLWTSP5FAIQANJIBK3C FOREIGN KEY (ID_EMPRESA) REFERENCES CLI_EMPRESA(ID_EMPRESA)
);


-- PUBLIC.CTA_PAGO DEFINITION

-- DROP TABLE

-- DROP TABLE PUBLIC.CTA_PAGO;

CREATE TABLE PUBLIC.CTA_PAGO (
	ID_PAGO BIGSERIAL NOT NULL,
	AUD_UPDATED_AT TIMESTAMP NOT NULL,
	AUD_UPDATED_BY VARCHAR(50) NOT NULL,
	AUD_VERSION INT8 NOT NULL,
	DESCRIPCION VARCHAR(300) NOT NULL,
	VF_ESTADO VARCHAR(30) NOT NULL,
	FECHA_ACEPTACION TIMESTAMP NULL,
	FECHA_REGISTRO TIMESTAMP NULL,
	VD_MONEDA VARCHAR(30) NOT NULL,
	MONTO INT4 NOT NULL,
	OBSERVACION VARCHAR(300) NULL,
	VD_TIPO VARCHAR(30) NOT NULL,
	ID_EMPRESA INT8 NOT NULL,
	CONSTRAINT CTA_PAGO_PKEY PRIMARY KEY (ID_PAGO),
	CONSTRAINT FKN0453GQFUUF4QTSSEAPMJHFBM FOREIGN KEY (ID_EMPRESA) REFERENCES CLI_EMPRESA(ID_EMPRESA)
);


-- PUBLIC.PAR_VALOR DEFINITION

-- DROP TABLE

-- DROP TABLE PUBLIC.PAR_VALOR;

CREATE TABLE PUBLIC.PAR_VALOR (
	ID_VALOR BIGSERIAL NOT NULL,
	AUD_UPDATED_AT TIMESTAMP NOT NULL,
	AUD_UPDATED_BY VARCHAR(50) NOT NULL,
	AUD_VERSION INT8 NOT NULL,
	DESCRIPCION VARCHAR(300) NOT NULL,
	VF_ESTADO VARCHAR(30) NOT NULL,
	ETIQUETA VARCHAR(300) NULL,
	ORDEN INT4 NULL,
	PADRE VARCHAR(50) NULL,
	VALOR VARCHAR(50) NULL,
	ID_DOMINIO INT8 NOT NULL,
	CONSTRAINT PAR_VALOR_PKEY PRIMARY KEY (ID_VALOR),
	CONSTRAINT FK7N62YMP9GIOL803PPKWUJBF9V FOREIGN KEY (ID_DOMINIO) REFERENCES PAR_DOMINIO(ID_DOMINIO)
);


-- PUBLIC.REG_REGISTRO DEFINITION

-- DROP TABLE

-- DROP TABLE PUBLIC.REG_REGISTRO;

CREATE TABLE PUBLIC.REG_REGISTRO (
	ID_REGISTRO BIGSERIAL NOT NULL,
	AUD_UPDATED_AT TIMESTAMP NOT NULL,
	AUD_UPDATED_BY VARCHAR(50) NOT NULL,
	AUD_VERSION INT8 NOT NULL,
	CODIGO VARCHAR(50) NOT NULL,
	DESCRIPCION VARCHAR(300) NOT NULL,
	VF_ESTADO VARCHAR(30) NOT NULL,
	FECHA_EMISION TIMESTAMP NULL,
	FECHA_SOLICITUD TIMESTAMP NULL,
	FECHA_VENCIMIENTO TIMESTAMP NULL,
	VD_ORIGEN VARCHAR(30) NOT NULL,
	VD_TIPO VARCHAR(30) NOT NULL,
	ID_EMPRESA INT8 NOT NULL,
	ID_PAGO INT8 NULL,
	CONSTRAINT REG_REGISTRO_PKEY PRIMARY KEY (ID_REGISTRO),
	CONSTRAINT FKEEK1G72FBPQLQ8Y10ARM2TWYH FOREIGN KEY (ID_PAGO) REFERENCES CTA_PAGO(ID_PAGO),
	CONSTRAINT FKFYQB0417DY0WP7VK0PLYC5ITN FOREIGN KEY (ID_EMPRESA) REFERENCES CLI_EMPRESA(ID_EMPRESA)
);


-- PUBLIC.SEG_USUARIO DEFINITION

-- DROP TABLE

-- DROP TABLE PUBLIC.SEG_USUARIO;

CREATE TABLE PUBLIC.SEG_USUARIO (
	ID_USUARIO BIGSERIAL NOT NULL,
	AUD_UPDATED_AT TIMESTAMP NOT NULL,
	AUD_UPDATED_BY VARCHAR(50) NOT NULL,
	AUD_VERSION INT8 NOT NULL,
	CLAVE_ACCESO VARCHAR(100) NOT NULL,
	CORREO_ELECTRONICO VARCHAR(100) NOT NULL,
	VF_ESTADO VARCHAR(30) NOT NULL,
	VD_TIPO VARCHAR(30) NOT NULL,
	ID_PERSONA INT8 NOT NULL,
	CONSTRAINT SEG_USUARIO_PKEY PRIMARY KEY (ID_USUARIO),
	CONSTRAINT FKH65VF2KGGGA6ODRDPPXGBPU86 FOREIGN KEY (ID_PERSONA) REFERENCES SEG_PERSONA(ID_PERSONA)
);


-- PUBLIC.CTA_DEPOSITO DEFINITION

-- DROP TABLE

-- DROP TABLE PUBLIC.CTA_DEPOSITO;

CREATE TABLE PUBLIC.CTA_DEPOSITO (
	ID_DEPOSITO BIGSERIAL NOT NULL,
	AUD_UPDATED_AT TIMESTAMP NOT NULL,
	AUD_UPDATED_BY VARCHAR(50) NOT NULL,
	AUD_VERSION INT8 NOT NULL,
	COMPROBANTE VARCHAR(50) NULL,
	VD_CUENTA VARCHAR(30) NOT NULL,
	DESCRIPCION VARCHAR(300) NOT NULL,
	CONTENIDO_ARCHIVO OID NULL,
	NOMBRE_ARCHIVO VARCHAR(50) NULL,
	TIPO_ARCHIVO VARCHAR(50) NULL,
	VF_ESTADO VARCHAR(30) NOT NULL,
	FECHA_DEPOSITO TIMESTAMP NULL,
	FECHA_REGISTRO TIMESTAMP NULL,
	FECHA_VERIFICACION TIMESTAMP NULL,
	VD_MONEDA VARCHAR(30) NOT NULL,
	MONTO FLOAT8 NULL,
	ID_PAGO INT8 NOT NULL,
	CONSTRAINT CTA_DEPOSITO_PKEY PRIMARY KEY (ID_DEPOSITO),
	CONSTRAINT FKPWHACN2EEKD1CGK31FODB2I02 FOREIGN KEY (ID_PAGO) REFERENCES CTA_PAGO(ID_PAGO)
);


-- PUBLIC.LOG_SESION DEFINITION

-- DROP TABLE

-- DROP TABLE PUBLIC.LOG_SESION;

CREATE TABLE PUBLIC.LOG_SESION (
	ID_SESION BIGSERIAL NOT NULL,
	AUD_UPDATED_AT TIMESTAMP NOT NULL,
	AUD_UPDATED_BY VARCHAR(50) NOT NULL,
	AUD_VERSION INT8 NOT NULL,
	VF_ESTADO VARCHAR(30) NOT NULL,
	FECHA_LOGIN TIMESTAMP NOT NULL,
	FECHA_LOGOUT TIMESTAMP NULL,
	ID_USUARIO INT8 NOT NULL,
	CONSTRAINT LOG_SESION_PKEY PRIMARY KEY (ID_SESION),
	CONSTRAINT FKM7C7SXXNYE0SBR83G5CK5THRA FOREIGN KEY (ID_USUARIO) REFERENCES SEG_USUARIO(ID_USUARIO)
);


-- PUBLIC.REG_SEGUIMIENTO DEFINITION

-- DROP TABLE

-- DROP TABLE PUBLIC.REG_SEGUIMIENTO;

CREATE TABLE PUBLIC.REG_SEGUIMIENTO (
	ID_SEGUIMIENTO BIGSERIAL NOT NULL,
	AUD_UPDATED_AT TIMESTAMP NOT NULL,
	AUD_UPDATED_BY VARCHAR(50) NOT NULL,
	AUD_VERSION INT8 NOT NULL,
	VF_ESTADO VARCHAR(30) NOT NULL,
	FECHA_ASIGNACION TIMESTAMP NOT NULL,
	FECHA_CIERRE TIMESTAMP NULL,
	FECHA_RESPUESTA TIMESTAMP NULL,
	ID_REFERENCIA VARCHAR(50) NULL,
	REFERENCIA VARCHAR(50) NULL,
	VD_TIPO VARCHAR(30) NOT NULL,
	ID_USUARIO INT8 NOT NULL,
	CONSTRAINT REG_SEGUIMIENTO_PKEY PRIMARY KEY (ID_SEGUIMIENTO),
	CONSTRAINT FKO9UVRC8M6QJ38WED25YTYQHKC FOREIGN KEY (ID_USUARIO) REFERENCES SEG_USUARIO(ID_USUARIO)
);


-- PUBLIC.SEG_OPERADOR DEFINITION

-- DROP TABLE

-- DROP TABLE PUBLIC.SEG_OPERADOR;

CREATE TABLE PUBLIC.SEG_OPERADOR (
	ID_OPERADOR BIGSERIAL NOT NULL,
	AUD_UPDATED_AT TIMESTAMP NOT NULL,
	AUD_UPDATED_BY VARCHAR(50) NOT NULL,
	AUD_VERSION INT8 NOT NULL,
	CORREO_ELECTRONICO VARCHAR(100) NULL,
	VF_ESTADO VARCHAR(30) NOT NULL,
	FECHA_DESDE TIMESTAMP NULL,
	FECHA_HASTA TIMESTAMP NULL,
	FECHA_RESPUESTA TIMESTAMP NULL,
	FECHA_SOLICITUD TIMESTAMP NULL,
	NOMBRE_CARGO VARCHAR(150) NOT NULL,
	NUMERO_DOCUMENTO VARCHAR(100) NULL,
	VD_PERFIL VARCHAR(30) NOT NULL,
	ID_EMPRESA INT8 NOT NULL,
	ID_USUARIO INT8 NULL,
	CONSTRAINT SEG_OPERADOR_PKEY PRIMARY KEY (ID_OPERADOR),
	CONSTRAINT FK6PWWX9IVQL04SMS2YA8KI5SMO FOREIGN KEY (ID_USUARIO) REFERENCES SEG_USUARIO(ID_USUARIO),
	CONSTRAINT FKBN746AOXY41HH1818W7YGNPE1 FOREIGN KEY (ID_EMPRESA) REFERENCES CLI_EMPRESA(ID_EMPRESA)
);


-- PUBLIC.LOG_EVENTO DEFINITION

-- DROP TABLE

-- DROP TABLE PUBLIC.LOG_EVENTO;

CREATE TABLE PUBLIC.LOG_EVENTO (
	ID_EVENTO BIGSERIAL NOT NULL,
	AUD_UPDATED_AT TIMESTAMP NOT NULL,
	AUD_UPDATED_BY VARCHAR(50) NOT NULL,
	AUD_VERSION INT8 NOT NULL,
	FECHA_EVENTO TIMESTAMP NULL,
	OPERACION VARCHAR(100) NULL,
	ID_SESION INT8 NOT NULL,
	CONSTRAINT LOG_EVENTO_PKEY PRIMARY KEY (ID_EVENTO),
	CONSTRAINT FKCVY2EF6J94EGBAXYTLW1WQ9YS FOREIGN KEY (ID_SESION) REFERENCES LOG_SESION(ID_SESION)
);


-- PUBLIC.LOG_CAMBIO DEFINITION

-- DROP TABLE

-- DROP TABLE PUBLIC.LOG_CAMBIO;

CREATE TABLE PUBLIC.LOG_CAMBIO (
	ID_CAMBIO BIGSERIAL NOT NULL,
	AUD_UPDATED_AT TIMESTAMP NOT NULL,
	AUD_UPDATED_BY VARCHAR(50) NOT NULL,
	AUD_VERSION INT8 NOT NULL,
	NOMBRE_COLUMNA VARCHAR(50) NULL,
	NOMBRE_TABLA VARCHAR(50) NULL,
	VALOR_ACTUAL VARCHAR(300) NULL,
	VALOR_PREVIO VARCHAR(300) NULL,
	ID_EVENTO INT8 NOT NULL,
	CONSTRAINT LOG_CAMBIO_PKEY PRIMARY KEY (ID_CAMBIO),
	CONSTRAINT FK7K8FPMANGG2BF8URTAI2B239Q FOREIGN KEY (ID_EVENTO) REFERENCES LOG_EVENTO(ID_EVENTO)
);
