CREATE TABLE PIV_USUARIO_ROL (
    ID_USUARIO_ROL BIGINT IDENTITY NOT NULL,    
    ID_USUARIO BIGINT,
    ID_ROL BIGINT,
    PRIMARY KEY (ID_USUARIO_ROL)
);

CREATE TABLE REG_ROL (
    ID_ROL BIGINT IDENTITY NOT NULL,    
    NOMBRE VARCHAR,
    DESCRIPCION VARCHAR(500),
    PRIMARY KEY (ID_ROL)
);

CREATE TABLE PIV_ROL_PERMISO (
    ID_RO_PERMISO BIGINT IDENTITY NOT NULL,    
    ID_ROL BIGINT,
    ID_MENU BIGINT,
    ID_RECURSO BIGINT,
    PRIMARY KEY (ID_ROL)
);

CREATE TABLE REG_MENU (
    ID_MENU BIGINT IDENTITY NOT NULL, 
    NOMBRE VARCHAR,
    DESCRIPCION VARCHAR(500),
    TIPO_MENU VARCHAR,
    ID_MENU_PADRE BIGINT,
    ICONO VARCHAR,
    COLOR VARCHAR,
    ID_APLICACION BIGINT,
    PRIMARY KEY (ID_MENU)
);

CREATE TABLE REG_RECURSO (
    ID_RECURSO BIGINT IDENTITY NOT NULL, 
    NOMBRE VARCHAR,
    DESCRIPCION VARCHAR(500),
    RUTA VARCHAR(100),
    TIPO_RECURSO VARCHAR,
    ID_APLICACION BIGINT,
    PRIMARY KEY (ID_MENU)
);

CREATE TABLE REG_APLICACION (
    ID_APLICACION BIGINT IDENTITY NOT NULL,    
    NOMBRE VARCHAR,
    DESCRIPCION VARCHAR(500),
    TIPO VARCHAR,
    PRIMARY KEY (ID_APLICACION)
);


ALTER TABLE
    PIV_USUARIO_ROL
ADD
    CONSTRAINT FK_PIV_USUARIO_ROL_ID_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES SEG_USUARIO (ID_USUARIO);

ALTER TABLE
    PIV_USUARIO_ROL
ADD
    CONSTRAINT FK_PIV_USUARIO_ROL_ID_ROL FOREIGN KEY (ID_ROL) REFERENCES REG_ROL (ID_ROL);

ALTER TABLE
    PIV_ROL_PERMISO
ADD
    CONSTRAINT FK_PIV_ROL_PERMISO_ID_ROL FOREIGN KEY (ID_ROL) REFERENCES REG_ROL (ID_ROL);

ALTER TABLE
    PIV_ROL_PERMISO
ADD
    CONSTRAINT FK_PIV_ROL_PERMISO_ID_MENU FOREIGN KEY (ID_MENU) REFERENCES REG_MENU (ID_MENU);


ALTER TABLE
    PIV_ROL_PERMISO
ADD
    CONSTRAINT FK_PIV_ROL_PERMISO_ID_RECURSO FOREIGN KEY (ID_RECURSO) REFERENCES REG_RECURSO (ID_RECURSO);


ALTER TABLE
    REG_MENU
ADD
    CONSTRAINT FK_REG_MENU_ID_APLICACION FOREIGN KEY (ID_APLICACION) REFERENCES REG_APLICACION (ID_APLICACION);

ALTER TABLE
    REG_RECURSO
ADD
    CONSTRAINT FK_REG_RECURSO_ID_APLICACION FOREIGN KEY (ID_APLICACION) REFERENCES REG_APLICACION (ID_APLICACION);
