CREATE OR REPLACE VIEW VIEW_USUARIO AS
SELECT CORREO_ELECTRONICO, CLAVE_ACCESO
FROM SEG_USUARIO
WHERE VF_ESTADO  = 'ACT';


CREATE OR REPLACE VIEW VIEW_PERMISO AS
SELECT 'ACCESO_WEB' CODIGO, 'ROLES' DESCRIPCION, CORREO_ELECTRONICO
FROM SEG_USUARIO
WHERE VF_ESTADO  = 'ACT';

